### ISSUE TITLE
Load Apexcharts via directinclude, but "define" on window exist.

### ISSUE THREAD

**Issue by jogibear9988** [apexcharts/apexcharts.js#1848]
I want to include ApexChart via direct "<script>" include into html.

But it does not define the ApexChart gobaly on window.

This happens cause of this line:
https://github.com/apexcharts/apexcharts.js/blob/65c8292ef3955f576ef12f0cd2efa5915a141c07/dist/apexcharts.js#L8

Because I also included "monaco" editor of VSCode, the "define" and "define.amd" are set.

How can I solve this?
I cannot clear define on window (like window.define=null) or monaco editor will not work.

**Comment by jogibear9988** [comment]
I tried to use ESM module via

     await import('../../../node_modules/apexcharts/dist/apexcharts.esm.js');

but then I got this error:

apexcharts.esm.js:10 Uncaught (in promise) ReferenceError: SVG is not defined
    at apexcharts.esm.js:10
    at apexcharts.esm.js:10

**Comment by sbruyere** [comment]
I've got the same issue with no solution:
blazor.server.js:1 [2024-05-28T15:10:23.337Z] Error: Microsoft.JSInterop.JSException: Can only have one anonymous define call per script file
Error: Can only have one anonymous define call per script file
    at c.enqueueDefineAnonymousModule (https://localhost:7217/_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js:8:4917)
    at p (https://localhost:7217/_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js:9:1802)
    at https://localhost:7217/_content/Blazor-ApexCharts/js/apexcharts.esm.js:6:540372
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at ApexCharts.ApexChart`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
