### ISSUE TITLE
npm run start npm ERR! missing script: start

### ISSUE THREAD

**Issue by yjiangnan** [apexcharts/apexcharts.js#281]
I follow your doc to install on Mac OS X, but got an error after running `npm run start`:
```
JiangNaokRetina:apexcharts.js jiangnan$ git clone https://github.com/apexcharts/apexcharts.js.git
Cloning into 'apexcharts.js'...
remote: Enumerating objects: 279, done.
remote: Counting objects: 100% (279/279), done.
remote: Compressing objects: 100% (186/186), done.
remote: Total 6065 (delta 148), reused 182 (delta 89), pack-reused 5786
Receiving objects: 100% (6065/6065), 9.00 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (4268/4268), done.
JiangNaokRetina:apexcharts.js jiangnan$ cd apexcharts.js/
JiangNaokRetina:apexcharts.js jiangnan$ npm install

> fsevents@1.2.4 install /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.7.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> puppeteer@1.11.0 install /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js/node_modules/puppeteer
> node install.js

Downloading Chromium r609904 - 82.7 Mb [====================] 100% 0.0s
Chromium downloaded to /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js/node_modules/puppeteer/.local-chromium/mac-609904

> puppeteer-core@1.11.0 install /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js/node_modules/puppeteer-core
> node install.js

added 1295 packages from 662 contributors and audited 23100 packages in 60.638s
found 0 vulnerabilities

JiangNaokRetina:apexcharts.js jiangnan$ npm run start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jiangnan/.npm/_logs/2019-01-20T16_21_02_451Z-debug.log
```
The log file contains:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.5.0
3 info using node@v11.7.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:115:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:418:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:373:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:416:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:364:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:90:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
5 verbose cwd /Users/jiangnan/Documents/software/workspace/apexcharts.js/apexcharts.js
6 verbose Darwin 16.5.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
8 verbose node v11.7.0
9 verbose npm  v6.5.0
10 error missing script: start
11 verbose exit [ 1, true ]
/Use
```

**Comment by junedchhipa** [comment]
Sorry, `npm run start` is incorrect and has been changed to

```bash
npm run dev
```
