### ISSUE TITLE
Download to CSV is working

### ISSUE THREAD

**Issue by jaidevjk** [apexcharts/apexcharts.js#4123]
**Downloading the data on clicking download to csv .**

As soon as the chart is loaded, if we click the toggle button on the top on righthand side of the chart, and on clicking download to csv - it is not downloading rather it will give you error as below.

**_**_### Cannot assign to read only property 'data' of object '#<Object>'
TypeError: Cannot assign to read only property 'data' of object '#<Object>'
    at m (http://localhost:3000/static/js/vendors-node_modules_react-apexcharts_dist_react-apexcharts_min_js.chunk.js:5803:22)
    at http://localhost:3000/static/js/vendors-node_modules_react-apexcharts_dist_react-apexcharts_min_js.chunk.js:5822:34
    at Array.map (<anonymous>)
    at t.value (http://localhost:3000/static/js/vendors-node_modules_react-apexcharts_dist_react-apexcharts_min_js.chunk.js:5821:115)
    at t.value (http://localhost:3000/static/js/vendors-node_modules_react-apexcharts_dist_react-apexcharts_min_js.chunk.js:8310:15)_**_**

It should get dwonloaded if the chart is loaded already.

![image](https://github.com/apexcharts/apexcharts.js/assets/102529250/6a3f6275-7cb2-4f76-b273-764ccc806af1)

The below image is the chart loaded.
![image](https://github.com/apexcharts/apexcharts.js/assets/102529250/06a17167-b493-460c-a552-a58c643e3ba3)

Am looking for a better suggestion or a good solution for the issue....Please respond as soon as possible.

Thank you.

**Comment by brianlagunas** [comment]
Did not provide required reproduction
