### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'querySelectorAll')

### ISSUE THREAD

**Issue by georgioua** [apexcharts/apexcharts.js#4478]
t.globals.previousPaths = [];
                ["line", "area", "bar", "rangebar", "rangeArea", "candlestick", "radar"].forEach((function(i) {
                    for (var a, s = (a = i,
                    t.globals.dom.baseEl.querySelectorAll(".apexcharts-".concat(a, "-series .apexcharts-series"))), r = 0; r < s.length; r++)
                        e(s, r, i)
                }
                )),

An interesting event occurred while finding a menu item, menu item is undefined. If you don't want this to happen, have you named all your menu items correctly? Original menu: [object Object], mnu: [object Object], key: dashboard_page_.
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.reset (employee.bundle.js:49508:8477)
    at i.reset (employee.bundle.js:34074:31)
    at employee.bundle.js:33958:48Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.reset (employee.bundle.js:49508:8477)
    at i.reset (employee.bundle.js:34074:31)
    at employee.bundle.js:33992:49Understand this error
apexcharts@latest:6 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Function.value (apexcharts@latest:6:5696)
    at Function.value (apexcharts@latest:6:5762)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5762)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5916)
    at Function.value (apexcharts@latest:6:5916)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:424818
    at Array.forEach (<anonymous>)
    at apexcharts@latest:6:424694
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:424548)
    at t.value (apexcharts@latest:14:41997)
    at t.populate (employee.bundle.js:49508:8477)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.populate (employee.bundle.js:49508:8477)
    at t.populate (employee.bundle.js:34301:31)
    at HTMLDivElement.<anonymous> (employee.bundle.js:34040:21)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.populate (employee.bundle.js:49508:8477)
    at t.populate (employee.bundle.js:34301:31)
    at HTMLDivElement.<anonymous> (employee.bundle.js:34040:21)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.reset (employee.bundle.js:49508:8477)
    at i.reset (employee.bundle.js:34074:31)
    at employee.bundle.js:33992:49Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:424818
    at Array.forEach (<anonymous>)
    at apexcharts@latest:6:424694
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:424548)
    at t.value (apexcharts@latest:14:41997)
    at t.populate (employee.bundle.js:49508:8477)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.populate (employee.bundle.js:49508:8477)
    at t.populate (employee.bundle.js:34301:31)
    at HTMLDivElement.<anonymous> (employee.bundle.js:34040:21)Understand this error
apexcharts@latest:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelectorAll')
    at apexcharts@latest:6:122655
    at Array.forEach (<anonymous>)
    at t.value (apexcharts@latest:6:122596)
    at apexcharts@latest:6:425962
    at new Promise (<anonymous>)
    at t.value (apexcharts@latest:6:425851)
    at t.value (apexcharts@latest:14:42347)
    at t.populate (employee.bundle.js:49508:8477)
    at t.populate (employee.bundle.js:34301:31)
    at HTMLDivElement.<anonymous> (employee.bundle.js:34040:21)Understand this error

**Comment by brianlagunas** [comment]
Did not follow bug template instructions
