### ISSUE TITLE
Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'node')]

### ISSUE THREAD

**Issue by AlbajramiKevin** [apexcharts/apexcharts.js#4731]
### Description

Build a test for the RadarChart as shown below. Running the test throws this issue: 
`Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'node')]
    at reportException (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at innerInvokeEventListeners (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:353:9)
    at invokeEventListeners (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
    at HTMLUnknownElementImpl._dispatch (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
    at HTMLUnknownElementImpl.dispatchEvent (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:104:17)
    at HTMLUnknownElement.dispatchEvent (/home/kevin/pimo/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:241:34)
    at Object.invokeGuardedCallbackDev (/home/kevin/pimo/node_modules/react-dom/cjs/react-dom.development.js:4213:16)
    at invokeGuardedCallback (/home/kevin/pimo/node_modules/react-dom/cjs/react-dom.development.js:4277:31)
    at reportUncaughtErrorInDEV (/home/kevin/pimo/node_modules/react-dom/cjs/react-dom.development.js:22877:5)
    at captureCommitPhaseError (/home/kevin/pimo/node_modules/react-dom/cjs/react-dom.development.js:27165:5`

Other types of chart pass the tests fine
### Steps to Reproduce

1. just build a simplistic test case for the radar chart as below
import { ApexOptions } from "apexcharts";

import { Card, CardContent, CardContentProps } from "../../molecules";

export interface RadarChartProps {
  /** Value of series */
  series: { name: string; data: number[] }[];
  /** Chart's colors */
  colors?: string[];
  /** Chart's labels */
  labels: string[];
}

``export const RadarChart: PimoReactComponent<RadarChartProps> = ({

  series,
  colors,
  labels,

}) => {
  const options: ApexOptions = {
    chart: {
      type: "radar",
      toolbar: {
        show: false,
      },
    },
    yaxis: {
      max: 5,
      min: 0,
    },
    colors,
    labels,
    legend: { show: true },
    dataLabels: { enabled: false },
    tooltip: {
      fillSeriesColor: false,
      theme: "light",
    },
  };

  return (
    <ReactApexChart
      options={options}
      series={series}
      type="radar"
      height={450}
      width={450}
    />
  );
};

export default RadarChart;
``
`import { render } from "@testing-library/react";

import { RadarChart } from "./radar-chart";

describe("RadarChart", () => {
  it("should render", () => {
    const { baseElement } = render(
      <RadarChart
        title="Radar Chart"
        series={[{ name: "series 1", data: [0, 1, 2, 3] }]}
        labels={["0", "1", "2", "3"]}
      />
    );
    expect(baseElement).toBeTruthy();
  });
});
` 

### Expected Behavior
test to run succesfully
### Actual Behavior
test fails

**Comment by katerberg** [comment]
This has happened for us locally as well. Did you find a solution @AlbajramiKevin?

**Comment by kalbajrami** [comment]
@katerberg wellI didnt really solve it, however it did seem like an issue that appeared only on testing, and this was a far from crucial aspect of what I was building, hence I didnt have the resources to put actual effort. I instead just replaced the react-charts with a div to make the tests pass
`vi.mock("react-apexcharts", () => ({
  __esModule: true,
  default: () => <div />,
}));`

If you have the time find a proper solution would appreciate to take a look at it.

**Comment by katerberg** [comment]
Thanks! I was leaning towards mocking it out as well, but would prefer to mock out the `SVG` API if that's the issue. I don't know `apexcharts` internals well enough to track those down like I did with the resize observers last time. :(
