### ISSUE TITLE
updateSeries stopped working after one of the most recent commits

### ISSUE THREAD

**Issue by noefp** [apexcharts/apexcharts.js#4866]
### Description

updateSeries stopped working after one of the most recent commits

### Steps to Reproduce

my_chart.updateSeries(
  new_series_data
)

### Expected Behavior
The plot renders again showing the new series data

### Actual Behavior
The plot does not update the data

### Reproduction Link

For example, at:
https://mangobase.org/easy_gdb/tools/expression/expression_input.php

Click in Get Expression.

Then open the Replicates section and change any of the gene names in the select. Usually that would update the data in the plot. It still works with an old version of apexcharts.min.js installed locally, but it stopped working recently using the cdn link.

**Comment by junedchhipa** [comment]
Can you create a reproducible codepen?

**Comment by TheodoreRed** [comment]
I am seeing a similar problem.

**Comment by Rakesh-HR** [comment]
I am experiencing the same issue as well. The console log from @noefp's reproduction is identical to mine. Changing the version back to 4.1.0 has worked for me too.

**Comment by djowebdev** [comment]
Same for me, now including explicitly https://cdn.jsdelivr.net/npm/apexcharts@4.1.0/dist/apexcharts.min.js works again. 

Error message I get:

`apexcharts:6 Uncaught TypeError: Cannot read properties of undefined (reading '0')`

Failing here: 
`chart.updateSeries([{
                      data: chartData.seriesData[0].data,
                      name: chartData.seriesName,
                  }]);`

**Comment by minhdqtt** [comment]
same with me, and I must back to 4.1.0. The error is:
apexcharts.min.js:6 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at apexcharts.min.js:6:518169
    at Array.map (<anonymous>)
    at t.value (apexcharts.min.js:6:518088)
    at t.value (apexcharts.min.js:38:35390)

**Comment by erwal45** [comment]
hi, same error for me, back to 4.1.0

**Comment by junedchhipa** [comment]
Can anyone test with the latest version 4.4.0 and report if it works?

**Comment by rhuliyar** [comment]
Seems to be working now

**Comment by Rakesh-HR** [comment]
Seems to be working now
